### ISSUE TITLE
MSRS  Dataset (VIF) Performance Different

### ISSUE THREAD

**Issue by challow0** [Linfeng-Tang/SwinFusion#3]
HI~ 
      Thanks for your work~ When I tried to reproduce the result on the MSRS dataset, I got a different performance compared with yours. Here are my results.

```
         Your            Mine
SSIM     0.9676         0.957
PSNR     64.4063       63.778
Q_abf    0.6428         0.632
FMI      0.9308         0.929
```

Can you help me to figure it out? Thank you.

**Comment by Linfeng-Tang** [comment]
I'm very sorry, I don't know why this issue is occurring. Did you use the pre-trained model I provided for testing?

**Comment by jyyuan666** [comment]
请问您是怎么运行成功这个代码的？MSRS数据集

**Comment by LittlePika** [comment]
Hello, thank you for providing the paper as well as the public code. I get this error message as well. When running the program with the configuration in_channel = 1, this works. When changing to in_channel=3 one gets the error message attached below.

In my opinion, this sounds like too few weights in the model available in git for VIF. 
How can I get the weights to use with in_channel=3? 
 
Thanks in advance. 

loading model from ./Model/Infrared_Visible_Fusion/Infrared_Visible_Fusion/models/
in_chans:  3
.local/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3190.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "./SwinFusion/test_swinfusion.py", line 153, in <module>
    main()
  File "./SwinFusion/test_swinfusion.py", line 50, in main
    model = define_model(args)
  File "./SwinFusion/test_swinfusion.py", line 94, in define_model
    model.load_state_dict(pretrained_model[param_key_g] if param_key_g in pretrained_model.keys() else pretrained_model, strict=True)
  File ".local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SwinFusion:
        size mismatch for conv_first1_A.weight: copying a param with shape torch.Size([30, 1, 3, 3]) from checkpoint, the shape in current model is torch.Size([30, 3, 3, 3]).
        size mismatch for conv_first1_B.weight: copying a param with shape torch.Size([30, 1, 3, 3]) from checkpoint, the shape in current model is torch.Size([30, 3, 3, 3]).
        size mismatch for conv_last3.weight: copying a param with shape torch.Size([1, 15, 3, 3]) from checkpoint, the shape in current model is torch.Size([3, 15, 3, 3]).
        size mismatch for conv_last3.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([3]).

**Comment by Amano-Hina** [comment]
> HI~ Thanks for your work~ When I tried to reproduce the result on the MSRS dataset, I got a different performance compared with yours. Here are my results.
> 
> ```
>          Your            Mine
> SSIM     0.9676         0.957
> PSNR     64.4063       63.778
> Q_abf    0.6428         0.632
> FMI      0.9308         0.929
> ```
> 
> Can you help me to figure it out? Thank you.

I’d be grateful if you could let me know how to calcluate these data since the repository can't achieve this.
